{
    'name': 'Supplier Portal',
    'version': '1.0',
    'summary': 'Manage Suppliers, Offers, Demands, and Invoices',
    'description': 'Module for managing suppliers, their offers, and demands, with a backend interface and access control.',
    'author': 'DOUBLE-D',
    'category': 'Custom',
    'depends': ['base', 'web', 'mail', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/supplier_views.xml',
        'views/offer_views.xml',
        'views/demand_views.xml',
        'views/invoice_views.xml',
        'views/login_signup_templates.xml',
        'views/supplier_space_templates.xml',
        'views/offer_creation_templates.xml',
        'views/offer_details_templates.xml',
        'views/demand_details_templates.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
